name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 17, 21, 25]
        scala: [2.12.x, 2.13.x, 3.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: ${{matrix.java}}
    - uses: sbt/setup-sbt@v1
    - name: Test
      run: sbt ++${{matrix.scala}} test doc headerCheck versionPolicyCheck package
